# Generated by Django 5.1.1 on 2024-10-05 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('guest_list', 'Guest List (Free entry, front of queue)'), ('skip_list', 'Skip List (Pay for entry, front of queue)'), ('standard', 'Standard Ticket (Queue normally, pay for entry)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
