# Generated by Django 5.1.1 on 2024-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_ticket_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
