# Generated by Django 5.1.1 on 2024-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_ticket_buyer_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(blank=True, default='fc8d2cf499', max_length=10, null=True),
        ),
    ]
