# Generated by Django 5.1.1 on 2024-12-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(default='a2076ecb92', max_length=10, unique=True),
        ),
    ]
